apiVersion: coprctl/v1alpha1
kind: package-custom
metadata:
  name: nodejs-{{cookiecutter.package}}
spec:
  auto_rebuild: false
  projectname: "{{cookiecutter.copr}}"
  script-builddeps: "nodejs-npm{% if cookiecutter.builddeps %} {{cookiecutter.builddeps}}{% endif %}"
  script-chroot: fedora-latest-x86_64
  script-repos: "{{cookiecutter.repos}}"
  script-resultdir: ""
  script: |
    #!/usr/bin/env bash

    set -euxo pipefail

    package='{{cookiecutter.package}}'
    strategy='{{cookiecutter.strategy}}'

    version="$(npm view "${package}" version)"

    npx npm2rpm -n "${package}" -v "${version}" -s "${strategy}"

    # TODO: -o flag?
    mv npm2rpm/* ./
    rmdir npm2rpm

    # npm2rpm tries to be clever and list a specific version of the npm
    # package, unfortunately in f38 that package doesn't actually put npm
    # on the PATH
    cat "nodejs-${package}.spec" | sed 's/BuildRequires: %{?scl_prefix_nodejs}npm/BuildRequires: nodejs-npm/' > modified.spec
    mv modified.spec "nodejs-${package}.spec"
