# Build fortune dat files
build:
  ls ./fortunes/ | xargs -I '$path' strfile './fortunes/$path'  

# Clean fortune dat files
clean:
  rm ./fortunes/*.dat

# Tag the release with tito
tag:
  tito tag

_push_tag:
  git push origin --follow-tags

# Apply copr configuration
apply-copr:
  coprctl apply -f ./package.yml

# Publish the release with tito
build-copr: tag _push_tag
