# Test building the main branch with tito
test:
  tito build --rpm --test

# Tag the release with tito
tag:
  tito tag --use-version 4.34.1

_push_tag:
  git push origin --follow-tags

# Publish the release with tito
publish: tag _push_tag
