[package]
name = "korben"
description = "RIP 2010 - 2022"
license = "Apache-2.0"
version = "0.1.1"
authors = ["Josh Holbrook <josh.holbrook@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.86"
colored = "2.1.0"
markov = "1.1.0"
