#+title: Josh Holbrook's Public Software

* Hello
This repository contains most of my open source and source-available code.

For my GPL-compatible free software, check out [[https://github.com/jfhbrook/public-gpl][my GPL-compatible software
repository]].
* Contents
** anisotropy
This submodule contains my masters thesis. It is licensed under the Community
Research and Academic Programming License v0 Beta 0.
** college
These are various projects I worked on in college. Each project is "poorly
licensed" - ~count_crossings~ and ~nomograms~ have no licensing information at
all and ~super-four-bar-explorer~ has "Everything here's on the wtfpl" in the
comments - but if someone really needs it I'm happy to add licensing
information. Let me know.
** db_hooks
This is the toolset I made for myself to manage database stuff on my personal
machines. It is licensed under an Apache v2.0 license with additional
restrictions. See the included NOTICE file for details.
** fortune-mod
This is a collection of (small, but hopefully will grow) fortune files. I
intend to put them up on COPR but haven't done it yet.
** github-profile
This submodule contains my GitHub README profile. It is unlicensed but
source-available.
** gpl
This submodule contains my GPL-compatible free software projects.
** korben-twitter
This is the twitter bot which powers [[https://twitter.com/korbenisabird][@korbenisabird]].
It's written in rust, and licensed under an Apache 2.0 license.
** korbenware
A collection of scripts I use to glue my Linux desktop and general CLI experience
together. Available under a MPL v2.0 license.
** old-memes
old memes is an old-school Node.js anti-framework built around the good parts
of [[https://github.com/flatiron][flatiron]], a selection of classic [[https://github.com/substack][substack]] libraries and the few worthwhile
things I personally wrote between roughly 2009 and 2016 - with a targeted
dash of modern conveniences. It's a big project, so see [[./README.md][its README]] for more details.
** openscad
These are files I've written for OpenSCAD. So far, these are available under a
MPL v2.0 license with additional restrictions. See the included NOTICE file for
details.
** politics
These are projects I've done for political organizations.
*** ak-demo-favicon
This is an icon I made for the Alaska Young Democrats in 2013, intended to be
used by progressive and democratic-aligned people and organizations in Alaska
and inspired by the JavaScript logo. It's licensed under a Creative Commons CC0
1.0 Universal License.
*** nys-data-dump-howto.org
Are you a leftist organization in New York State and interested in working with
their open electoral data? This document details how to get your hands on
campaign disclosure reports and voter files and successfully load them into a
database for further exploration and processing. It is licensed under an
Anti-Capitalist Software License.
** PSeudo
This is a PowerShell module for privilege escalation in Windows 10, using named
pipes and a bunch of dirty tricks. It is based on code I found and saved from
the internet. It is licensed under an MIT Expat license with additional
restrictions. See the LICENSE file for details.
** pyee
This is a loose port of the Node.js EventEmitter with special support for
coroutines and concurrent programming. It is licensed under an MIT license.
** resume
This is my resume! This repository contains PDFs for my standard one-page resume
and a longer CV. It's written in LaTeX.
** twisted_ipython
This is a module that makes autoawait work in IPython using Twisted. It is
licened under a BSD 3-clause license with additional restrictions. See
the included NOTICE file for details.

For more information, read [[https://dev.to/jfhbrook/twistedipython-autoawait-in-jupyter-notebooks-with-twisted-lee][the blog post on dev.to]].
