set dotenv-load := true

tangle-directions := "open elisp.org in emacs and run C-c C-v to generate elisp snippets!"

elisp:
  if command -v org-tangle &> /dev/null; then org-tangle ./elisp.org || echo "warning, org-tangle failed - {{ tangle-directions }}"; else echo "warning, org-tangle not found - {{ tangle-directions }}"; fi

readme:
  pandoc -f org -t markdown README.org -o README.md

build: elisp readme
  cargo build

test: elisp readme
  cargo test

check: elisp readme
  cargo check

run *ARGS: elisp readme
  cargo run -- {{ ARGS }}

publish: elisp readme
  cargo publish --allow-dirty
