# Apply the COPR configuration
apply-copr:
  coprctl apply -f ./package.yml

# Build the package on COPR
build-copr:
  copr build-package joshiverse --name nodejs-licenseify

release:
  npm publish
  @just apply-copr
  @just build-copr
