apiVersion: coprctl/v1alpha1
kind: package-custom
metadata:
  name: rust-omsxctl
spec:
  auto_rebuild: false
  script-builddeps: rust2rpm rust-anyhow-devel rust-clap+derive-devel rust-colored-devel rust-glob-devel rust-rustyline-devel rust-tracing-devel rust-tracing-subscriber-devel rust-xml-rs-devel
  script-chroot: fedora-latest-x86_64
  script-repos: ""
  script-resultdir: ""
  script: |
    #!/usr/bin/env bash

    set -euxo pipefail

    rust2rpm -s -t fedora omsxctl
