apiVersion: coprctl/v1alpha1
kind: package-pypi
metadata:
  name: python3-{{cookiecutter.package}}
spec:
  auto_rebuild: true
  projectname: {{cookiecutter.copr}}
  packagename: {{cookiecutter.package}}
  packageversion: {% if cookiecutter.version %}{{cookiecutter.version}}{% else %}null{% endif %}
  pythonversions:
    - "3"
  spec-generator: pyp2spec
  template: ""
