set dotenv-load := true
set shell := ["pwsh", "-c"]

install:
  ./scripts/Install.ps1

lint:
  & ./scripts/Activate.ps1; Invoke-ScriptAnalyzer -Path . -Recurse

format:
  & ./scripts/Activate.ps1; Invoke-ScriptAnalyzer -Fix -Path . -Recurse

start:
  cd service && func start

deploy:
  cd service && func azure functionapp publish "${VERBTIONARY_APP_NAME}"
