# Open a shell with bins in the PATH
shell:
  PATH="$(pwd)/bin:${PATH}" bash --login

# Tag the release with tito
tag:
  tito tag

_push_tag:
  git push origin --follow-tags

# Publish the release with tito
publish: tag _push_tag
