VERSION := "0.5.1"

# Open a shell with bins in the PATH
shell:
  PATH="$(pwd)/bin:${PATH}" bash --login

# Tag the release with tito
tag:
  tito tag --use-version '{{VERSION}}'

_push_tag:
  git push origin --follow-tags

# Apply copr configuration
apply:
  coprctl apply -f ./copr.yml

# Publish the release with tito
publish: tag _push_tag
