VERSION := "0.6.2"

# Open a shell with bins in the PATH
shell:
  PATH="$(pwd)/bin:${PATH}" bash --login

# Tag the release with tito
tag:
  tito tag --use-version '{{VERSION}}'

_push_tag:
  git push origin --follow-tags

# Apply copr configuration
apply-copr:
  coprctl apply -f ./package.yml

build-copr: apply-copr
  copr build-package jfhbrook/joshiverse --name 'korbenware'

# Publish the release with tito
publish: tag _push_tag build-copr
