# Lint with shellcheck
lint:
  shellcheck ./bin/coprctl

# Open a shell with bin in the PATH
shell:
  PATH="$(pwd)/bin:${PATH}" bash --login

# Tag the release with tito
tag:
  tito tag

_push_tag:
  git push origin --follow-tags

# Apply COPR configuration
apply-copr:
  ./bin/coprctl apply -f ./package.yml

# Tag and push a release with Tito and trigger a COPR build
build-copr: tag apply-copr _push_tag
  copr build-package jfhbrook/joshiverse --name coprctl
