[package]
name = "procmon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
