apiVersion: coprctl/v1alpha1
kind: package-custom
metadata:
  name: nodejs-exercise-bike
spec:
  auto_rebuild: false
  id: 2115974
  latest_build: null
  latest_succeeded_build: null
  ownername: jfhbrook
  projectname: joshiverse
  script-builddeps: nodejs-npm
  script-chroot: fedora-latest-x86_64
  script-repos: ""
  script-resultdir: ""
  script: |
    #!/usr/bin/env bash

    set -euxo pipefail

    name=exercise-bike
    strategy=bundle

    version="$(npm view "${name}" version)"

    npx npm2rpm -n "${name}" -v "${version}" -s "${strategy}"

    # TODO: -o flag?
    mv npm2rpm/* ./
    rmdir npm2rpm

    # npm2rpm tries to be clever and list a specific version of the npm
    # package, unfortunately in f38 that package doesn't actually put npm
    # on the PATH
    cat "nodejs-${name}.spec" | sed 's/BuildRequires: %{?scl_prefix_nodejs}npm/BuildRequires: nodejs-npm/' > modified.spec
    mv modified.spec "nodejs-${name}.spec"
