apiVersion: coprctl/v1alpha1
kind: package-custom
metadata:
  name: nodejs-exercise-bike
spec:
  auto_rebuild: false
  id: 2115974
  latest_build: null
  latest_succeeded_build: null
  ownername: jfhbrook
  projectname: joshiverse
  script-builddeps: nodejs-npm
  script-chroot: fedora-latest-x86_64
  script-repos: ""
  script-resultdir: ""
  script: |
    #!/usr/bin/env bash

    set -euxo pipefail

    package=exercise-bike
    strategy=bundle

    version="$(npm view "${package}" version)"

    npx npm2rpm -n "${package}" -v "${version}" -s "${strategy}"

    # TODO: -o flag?
    mv npm2rpm/* ./
    rmdir npm2rpm

    # 1. Use system npm instead of bundled npm
    # 2. License and doc paths are broken so don't include them
    cat "nodejs-${package}.spec" \
      | sed 's/BuildRequires: %{?scl_prefix_nodejs}npm/BuildRequires: nodejs-npm/' \
      | sed 's/\%license .*//' \
      | sed 's/\%doc .*//' \
      > modified.spec
    mv modified.spec "nodejs-${package}.spec"
