apiVersion: coprctl/v1alpha1
kind: project
metadata:
  name: joshiverse
spec:
  chroots:
    - "fedora-37-x86_64"
    - "fedora-38-x86_64"
  # TODO: allow specifying initial-pkgs on create
  # initial-pkgs: []
  description: "Josh Holbrook's personal package registry"
  instructions: "Nothing special - add the copr following the 'quick-enable' directions in the right rail, and start installing stuff!"
  # TODO: homepage and contact are unsupported by the CLI
  # homepage: "https://github.com/jfhbrook/public"
  # contact: "josh.holbrook@gmail.com"
  disable_createrepo: "n"
  enable-net: "off"
  unlisted-on-hp: "off"
  isolation: "default"
  bootstrap: "default"
  delete-after-days: ""
  module-hotfixes: "off"
  multilib: "off"
  fedora-review: "off"
  appstream: "off"
  follow-fedora-branching: "on"
  repos: []
  runtime-repo-dependencies: []
  pakt-forge-projects-allowed: []
